export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const LIST_PRODUCTS = "LIST_PRODUCTS";
export const SET_LIST_PRODUCTS = "SET_LIST_PRODUCTS";
